# Generated by Django 5.0.2 on 2026-05-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="截止時間"),
        ),
    ]
